name: Release version

on:
  workflow_dispatch:  # manual testing
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build Workspace on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build workspace member
        run: |
          echo "Building on ${{ matrix.os }}"
          cargo build --release -p pypam_ttysshca -p Authenticator -p Authenticator_cli

      - name: Unify lib name on Linux
        if: matrix.os == 'ubuntu-latest'
        run: mv target/release/libpypam_ttysshca.so target/release/pypam_ttysshca.so

      - name: Copy artifacts
        uses: softprops/action-gh-release@v1
        with:
          name: binaries
          files: |
            target/release/Authenticator
            target/release/Authenticator_cli
            target/release/pypam_ttysshca.so
            target/release/Authenticator.exe
            target/release/Authenticator_cli.exe
            target/release/pypam_ttysshca.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
